### ISSUE TITLE
Pack version is out of date

### ISSUE THREAD

**Issue by zmackie** [buildpacks/docs#113]
The slug <latest> doesn't seem to get updated when new releases of pack come out. I think it would be easier to just point to the brew tap and https://github.com/buildpacks/pack/releases/latest where necessary and leave out specific versions entirely

**Comment by jromero** [comment]
This isn't a bug. It's the fact that nothing is monitoring releases and "rebuilding" the docs site.

**Comment by jromero** [comment]
For more info, the pack version is automatically queried at build time.

**Comment by jromero** [comment]
We could also use JS to dynamically query it at render time.

**Comment by thephw** [comment]
@jromero Is the process currently manual? What are the steps?

**Comment by jromero** [comment]
Hi @thephw,

It's not, it is fetched at build time [here](https://github.com/buildpacks/docs/blob/master/Makefile#L4-L10). The problem seems to be that we haven't had any changes to this repo that would warrant building and deploying the site.

The ideal solution would be that something, maybe GitHub Actions, monitors the releases of pack and when a release occurs, builds and redeploys the site.

**Comment by dfreilich** [comment]
It seems that #115 points to the same issue. Closing this in favor of that.
