### ISSUE TITLE
Add Legacy Documentation

### ISSUE THREAD

**Issue by dfreilich** [buildpacks/docs#244]
## Summary

For legacy sake, it could be useful to have documentation pointing to the old Heroku and Cloud Foundry Buildpacks API, to help people understand how this is different

## What questions should this documentation answer?
- Where can I find information about the old specs?
- How is this different?

## Who is the target audience for this documentation?

- [ ] App Developer
- [x] Buildpack Author
- [ ] Operator
- [ ] Other:

## Additional Information

[Heroku Buildpacks API](https://devcenter.heroku.com/articles/buildpack-api)
[CloudFoundry Buildpacks](https://docs.cloudfoundry.org/buildpacks/understand-buildpacks.html)

**Comment by jromero** [comment]
After some careful consideration, I think we'd like to close this as "won't do". Since the opening of this issue there seems to be less desire or need to add this sort of referencing. If anything, we are afraid it would only cause more confusion.

If you disagree with this sentiment, please feel free to reopen and detail the reasoning andr implementation that would add value while minimizing confusion.
