### ISSUE TITLE
Typo in the `pack stack suggest` doc page

### ISSUE THREAD

**Issue by butonly** [buildpacks/docs#570]
**On Page:** [pack stack suggest](https://buildpacks.io/docs/tools/pack/cli/pack_stack_suggest/)

<img width="831" alt="image" src="https://user-images.githubusercontent.com/5998826/221415411-f84026a9-46de-4b11-953e-7aa406246b2f.png">

**Comment by Kanika637** [comment]
I would like to work on this.

**Comment by Kanika637** [comment]
I want to work on this issue!

**Comment by AidanDelaney** [comment]
Thanks @butonly, this issue comes from a typo in `pack`.  We autogen this part of the docs from `pack`.

The upstream change has landed in https://github.com/buildpacks/pack/commit/0997030f0bb0034f1149970ebe7a40142795d970 and was released in `pack` 0.29.  This should "solve itself" as soon as we merge any other change.

@Kanika637 if you'd like to help with our docs, I can find another good "first issue" for you?  Feel free to ping me on CNCF Slack.

**Comment by Kanika637** [comment]
> Thanks @butonly, this issue comes from a typo in `pack`. We autogen this part of the docs from `pack`.
> 
> The upstream change has landed in [buildpacks/pack@0997030](https://github.com/buildpacks/pack/commit/0997030f0bb0034f1149970ebe7a40142795d970) and was released in `pack` 0.29. This should "solve itself" as soon as we merge any other change.
> 
> @Kanika637 if you'd like to help with our docs, I can find another good "first issue" for you? Feel free to ping me on CNCF Slack.

Sure, would love to contribute.
