### ISSUE TITLE
Doc search returns broken links

### ISSUE THREAD

**Issue by ryanbrainard** [buildpacks/docs#668]
**On Page:** [Getting Started](https://buildpacks.io/docs/)

When using the doc search box in the upper left, there are many results that are returned with dead links. For example, type in `mirror` and click on one of links (e.g. https://buildpacks.io/docs/tools/pack/cli/pack_config_registry-mirrors_list/) and it is a 404.

<img width="1274" alt="2024-03-06_14-18-57" src="https://github.com/buildpacks/docs/assets/966764/4a32f339-7526-44a5-aabf-21b7e1aa60f4">

**Comment by natalieparellano** [comment]
Content lives at:
https://buildpacks.io/docs/for-platform-operators/how-to/integrate-ci/pack/cli/pack_config_registry-mirrors_list/

Search returns:
https://buildpacks.io/docs/tools/pack/cli/pack_config_registry-mirrors_list/

I think this [PR](https://github.com/buildpacks/docs/pull/662/files#diff-f84bedbf94f6550fd8c48d8c17e297a402281d8121aa438b7531576109cda604R25) unfortunately aliases each individual pack CLI page to https://buildpacks.io/docs/tools/pack instead of the corresponding `https://buildpacks.io/docs/tools/pack/cli/<pack_command_path>`

I believe the "correct" solution here is to figure out how to re-generate all our search results!

**Comment by ryanbrainard** [comment]
> I believe the "correct" solution here is to figure out how to re-generate all our search results!

@natalieparellano  Something else to note is that there are also a lot of broken links from [Google](https://www.google.com/search?q=buildpacks+pack+config+registry+mirror+list) and other docs, so if we can restore the URLs to their original location (instead of re-generating all our search results), it would probably be better.

**Comment by natalieparellano** [comment]
@ryanbrainard fair enough. I think https://github.com/buildpacks/docs/pull/671 will fix this. 

@AidanDelaney could you please take a look? 🙏🏼
